# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(max_length=200)),
                ('course_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('course_sem', models.IntegerField(max_length=200)),
                ('course_year', models.IntegerField(max_length=200)),
                ('course_deptid', models.IntegerField(max_length=200)),
                ('course_facid', models.IntegerField(max_length=200)),
                ('course_prog', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField(max_length=200)),
                ('fourse_name', models.CharField(max_length=200)),
                ('faculty_cont', models.IntegerField(max_length=200)),
                ('faculty_joindate', models.DateTimeField(max_length=200)),
                ('course_deptid', models.IntegerField(max_length=200)),
                ('course_desig', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.IntegerField(max_length=200)),
                ('login_pass', models.CharField(max_length=200)),
                ('login_role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('student_DOB', models.DateTimeField(max_length=200)),
                ('student_prog', models.CharField(max_length=200)),
                ('student_branch', models.CharField(max_length=200)),
                ('student_semester', models.IntegerField(max_length=200)),
                ('student_year', models.IntegerField(max_length=200)),
                ('pustudent_id', models.IntegerField(max_length=200)),
            ],
        ),
    ]
