# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_deptid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_facid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_sem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='course_deptid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_cont',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_joindate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='login',
            name='login_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='pustudent_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_DOB',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_year',
            field=models.IntegerField(),
        ),
    ]
