# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20171106_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_clas',
            field=models.IntegerField(default=0),
        ),
    ]
