# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_total_clas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='course_deptid',
            new_name='faculty_deptid',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='course_desig',
            new_name='faculty_desig',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='fourse_name',
            new_name='faculty_name',
        ),
    ]
