# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20171106_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pustudent_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course_id',
            field=models.IntegerField(),
        ),
    ]
